from_latest_tag = false
tag_prefix = "v"
ignore_merge_commits = true
branch_whitelist = ["main"]
pre_bump_hooks = []

post_bump_hooks = [
    "git push",
    "git push origin v{{version}}"
]

pre_package_bump_hooks = []
post_package_bump_hooks = []

[commit_types]

[changelog]
path = "CHANGELOG.md"
remote = "github.com"
repository = "drone-s2i-builder"
owner = "witcom-gmbh"
authors = [
    { signature = "Carsten Buchberger", username = "iceman91176" }
]

[bump_profiles]

[packages]
